config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#welcome'
  resources :journeys, only: [:index, :show] do
    resources :pois, only: [:index, :show]
  end
  namespace :artists do
    resources :journeys do
      resources :pois
    end
  end
  get 'styleguide', to: 'pages#styleguide'
  get 'testgmap', to: 'pages#test'
  get 'template', to: 'pages#template'
  get 'value', to: 'pages#value'
  #get 'welcome', to: 'pages#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  has_many :journey_pois
  has_many :pois, through: :journey_pois
  validates :name,  presence: true
  validates :description, presence: true
end

app/models/journey_poi.rb
class JourneyPOI < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :journey
  belongs_to :poi
  validates :name, presence: true
end

app/models/poi.rb
class POI < ApplicationRecord
  has_many :journey_pois
  has_many :journeys, through: :journey_pois
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, PhotoUploader

  has_many :journeys
  validates :pseudo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!

  def default_url_options
  { host: ENV["HOST"] || "localhost:3000" }
end

end

app/controllers/artists/journeys_controller.rb
class Artists::JourneysController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/artists/pois_controller.rb
class Artists::PoisController < ApplicationController
  def show

  end

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  def index
    @coordinates_hash = []
    @journeys = Journey.all
    @journeys.each do |journey|
    @coordinates_array = []
      journey.pois.each do |poi|
        latitude = poi.latitude
        longitude = poi.longitude
        @coordinates_array << [latitude , longitude]
      end
      @coordinates_hash << @coordinates_array
    end

  end

  def show
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    redirect_to journeys_path
  end

  def test
  end

  def template
  end


  def value
    @result = []
    # POI name for user
    # Journey name for user
    # Poi content
    # User avatar


    POI.where(latitude: params[:pos]).each do |poi|
      @user = {}
      poi_id = poi.id
      poi.journeys.each do |journey|
        contenu = journey.journey_pois.where(poi_id: poi_id).first
        @user = {
          journeyid: journey.id,
          #poiid: contenu.id,
          poiid: poi_id,
          avatar: journey.user.avatar.url,
          journeyname: journey.name,
          poiname: contenu.name,
          poiphoto: contenu.photo.url,
          poivideo: contenu.video,
          poitext: contenu.text,
          poisound: contenu.sound
        }
        @result << @user
      end
    end
    render :json => @result
  end
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  def show

    @poi         = POI.find(params[:id])
    @journey     = Journey.find(params[:journey_id])
    @journey_poi = @poi.journey_pois.find_by_journey_id(@journey.id)

    poi_index_for_journey = @journey.pois.index(@poi)

    next_poi_for_journey_index     = (poi_index_for_journey + 1) % @journey.pois.count
    previous_poi_for_journey_index = (poi_index_for_journey - 1) % @journey.pois.count

    @next_poi_for_journey     = @journey.pois[next_poi_for_journey_index]
    @previous_poi_for_journey = @journey.pois[previous_poi_for_journey_index]

    journey_index_for_poi = @poi.journeys.index(@journey)

    next_journey_for_poi_index      = (journey_index_for_poi + 1) % @poi.journeys.count
    previous_journey_for_poi_index  = (journey_index_for_poi - 1) % @poi.journeys.count

    @next_journey_for_poi     = @poi.journeys[next_journey_for_poi_index]
    @previous_journey_for_poi = @poi.journeys[previous_journey_for_poi_index]

    @coordinates_hash = []


    @coordinates_array = []
    @journey.pois.each do |poi|
      latitude = poi.latitude
      longitude = poi.longitude
      @coordinates_array << [latitude , longitude]
    end
    @coordinates_hash << @coordinates_array

  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/module MetaTagsHelper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/artists/journeys/create.html.erb
create

app/views/artists/journeys/show.html.erb
journey Show

app/views/artists/pois/create.html.erb
create

app/views/artists/pois/index.html.erb
<<<<<<< HEAD



=======
        <div class="map" id="map">
        </div>

        <div class="poi-footer ">

          <div class="poi-footer-user-change">
            <%= image_tag "logo.png",  alt: "user", class: "avatar-small" %>
          </div>
          <div class="poi-footer-title">
            <h4>Chateau des ducs de bretagne</h4>
          </div>
          <div class="poi-footer-user-change">
            <%= image_tag "logo.png",  alt: "user", class: "avatar-small" %>
          </div>
       </div>

      </div>
    </div>
  </div>
</div>
>>>>>>> 87681414b18ebd7af3d5e91b5ba8b723a480b128

app/views/artists/pois/new.html.erb
<div class="poi-container-full">
  <div class="row">

      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="container-height">
        <div class="banner">
          <div>
            <%= image_tag "logo.png",  alt: "user", class: "avatar-large" %>
          </div>
          <div class="banner-title">
            <h3>BALADE SOLITAIRE</h3>
            <p>par thomasloldu44</p>
          </div>
        </div>


        <div class="poi-body-contenu">

          <div class="container-poi">


            <div class="flex1">
               <i class="fa fa-font  btn-fa fa-5x  " aria-hidden="true"></i>
            </div>


            <div class="flex2">
              <i class="fa fa-youtube-play btn-fa icon-add-content" aria-hidden="true"></i>
              <p>Choisi ton média</p>
              <i class="fa fa-microphone btn-fa " aria-hidden="true"></i>
            </div>

            <div class="flex3">
              <i class="fa fa-camera btn-fa" aria-hidden="true"></i>

              <i class="fa fa-exclamation  btn-fa" aria-hidden="true"></i>
            </div>
          </div>

        </div>

        <div class="map" id="map">
       </div>

        <div class="footer ">

          <div class="footer-user-change">
            <i class="fa fa-angle-left btn-fa" aria-hidden="true"></i>
            <%= image_tag "logo.png",  alt: "user", class: "avatar-small" %>
          </div>
          <div class="footer-title">
            <h4>Chateau des ducs de bretagne</h4>
          </div>
          <div class="footer-user-change">
            <%= image_tag "logo.png",  alt: "user", class: "avatar-small" %>
            <i class="fa fa-angle-right btn-fa" aria-hidden="true"></i>
          </div>
       </div>

      </div>
    </div>
  </div>
</div>

app/views/journeys/destroy.html.erb
DESTROY 8!!!!!!!!!!!!

app/views/journeys/edit.html.erb
edit !!!!!!!

app/views/journeys/show.html.erb
<div class="row-no-padding">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <div class="full-map" id="map">
    </div>
    <div>
      <i class="fa fa-plus-circle btn-fa add-button" style=""aria-hidden="true"></i>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= meta_title %></title>

<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">



    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Abel|Fjalla+One|Jim+Nightshade" rel="stylesheet">
  </head>
  <body>
   <!--   render 'shared/navbar'  -->
    <!-- <= render 'shared/flashes' %> -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_API_GMAP"] %>"></script>
    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:js) %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/template.html.erb
<div class="container-full">

  <div class="row">


      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="container-height">

        <div class="banner">

          <div>

            <%= image_tag "logo.png",  alt: "user", class: "avatar-large" %>

          </div>

          <div class="banner-title">

            <h3>BALADE SOLITAIRE</h3>

            <p>par thomas loldu44</p>

          </div>

        </div>

        <div class="alt-banner">

        </div>

        <div class="body-contenu">

          <div class="body-description">

            <p>Tout a commencé par une envie de se balader dans Nantes sans but précis. Juste une découverte par l'errance.</p>

          </div>

          <hr class="padding-hr">

          <div class="body-media">

            <%= image_tag "media_template.png", class: "img-responsive-custom" %>

          </div>

         </div>

        <div class="map" id="map">

        </div>

        <div class="footer ">

          <div class="footer-user-change">

            <i class="fa fa-angle-left btn-fa" aria-hidden="true"></i>

            <%= image_tag "logo.png",  alt: "user", class: "avatar-small" %>

          </div>

          <div class="footer-title">

            <h4>Chateau des ducs de bretagne</h4>

          </div>

          <div class="footer-user-change">

            <%= image_tag "logo.png",  alt: "user", class: "avatar-small" %>

            <i class="fa fa-angle-right btn-fa" aria-hidden="true"></i>

          </div>

       </div>

      </div>

    </div>

  </div>

</div>

app/views/pages/test.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ex03-c</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="style4.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

<!-- GMAP -->


<!-- <div id="menu_wrapper">
  <div id="menu"> -->
<form method="get">
<input type="text" name="mystylegmap">
<input type="submit">
</form>
<!--
    <div id="menu_btn">MENU</div>
  </div>

</div>
 -->

<!-- style="width: 100%; height: 80vh;" -->
 <div id="map" style="width: 100%; height: 95vh;">
 </div>







    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_API_GMAP"] %>"></script>

  </body>
</html>

app/views/pages/welcome.html.erb
<style type="text/css">
@media screen and (max-width: 500px) {
  div{width:70%;}
}
@media screen and (max-device-width: 800px) {
  html { background: url("https://www.youtube.com/embed/rK-NrTkFa9c") #000 no-repeat center center fixed;}
  #bgvid { display: none; }
}
</style>


<!-- <video frameborder="0" allowfullscreen id="bgvid" playinline autoplay muted loop>
  <source src="https://www.youtube.com/embed/rK-NrTkFa9c" type="mp4">
  </video> -->

<div style="position: fixed; z-index: -99; width: 100%; height: 100%">
  <iframe frameborder="0" height="100%" width="100%"
    src="https://www.youtube.com/embed/X-87DNw5n7w?autoplay=1&controls=0&showinfo=0&autohide=1&frameborder=0&allowfullscreen=0&loop=1&playlist=X-87DNw5n7w">
  </iframe>
</div>
  <div id="welcome-wrapper">
    <div class="container-welcome text-center">
      <div class="container-content">
        <h1>City Stories</h1>
        <%= cl_image_tag("logo_citystories-03-02_al7idf.png", :width=>100, :crop=>"scale")%>
        <h4> Faites d'une ville votre page blanche. <br> Parcourez la selon le regard et les yeux d'un autre.</h4>
      </div>

      <div class="container-content">
        <h4> Racontez vous et racontez nous votre ville  à travers vos parcours.</h4>
        <%= link_to "Entrer", journeys_path, class: "button-enter"%>
      </div>
    </div>
  </div>

app/views/pois/index.html.erb
POI Index

app/views/pois/show.html.erb
<div class="containexer-full">
  <div class="row-no-padding">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="container-height">

          <% if @poi.journeys.count != 1 %>
            <div class="footer ">
              <div class="footer-user-change">

                <%= link_to journey_poi_path(@previous_journey_for_poi, @poi) do %>
                  <i class="fa fa-angle-left btn-fa" aria-hidden="true"></i>
                  <%= cl_image_tag @previous_journey_for_poi.user.avatar, class: "avatar-small" %>
                <% end %>

              </div>
              <div class="footer-title-show">
              <p>Changer de Parcours</p>
              </div>
              <div class="footer-user-change">
                <%= link_to journey_poi_path(@next_journey_for_poi, @poi) do %>

                  <%= cl_image_tag @next_journey_for_poi.user.avatar, class: "avatar-small" %>
                  <i class="fa fa-angle-right btn-fa" aria-hidden="true"></i>
                <% end %>
              </div>
            </div>
          <% end %>



        <div class="banner">
          <div>


            <%= cl_image_tag @journey.user.avatar, class: "avatar" %>
          </div>
          <div class="banner-title">


            <h3> <%= @journey.name %> </h3>

            <p>par <%= @journey.user.pseudo %> </p>

          </div>
        </div>
        <div class="map-show" id="map">
        </div>

        <div class="footer-show ">
          <div class="footer-user-change">
            <%= link_to journey_poi_path(@journey, @next_poi_for_journey) do %>
              <i class="fa fa-angle-left btn-fa fa-white" aria-hidden="true"></i>
            <% end %>
          </div>

          <div class="footer-title">
          <h4><%= @journey_poi.name%></h4>
          </div>

          <div class="footer-user-change">
            <%= link_to journey_poi_path(@journey, @next_poi_for_journey) do %>
            <i class="fa fa-angle-right btn-fa fa-white" aria-hidden="true"></i>
            <% end %>

          </div>
        </div>


        <div class="alt-banner">

        </div>

        <div class="body-contenu">

          <div class="body-description">

            <p><%= @journey_poi.description %></p>

          </div>

          <hr class="padding-hr">

          <div class="body-media">

            <div class="media">
            <%= cl_image_tag @journey_poi.photo, class: "media-fix-width" %>
            <% unless @journey_poi.text.nil? %>
            <div class="media-fix-width poesie"><%= simple_format @journey_poi.text %></div>
            <% end %>
            <% unless @journey_poi.video.nil? %>
            <div class="media-fix-width"><iframe width="560" height="315" src="<%= @journey_poi.video %>" frameborder="0"></iframe></div>
            <% end %>
            <% unless @journey_poi.sound.nil? %>
            <div class="media-fix-width"><iframe width=“100%” height=“450" scrolling=“no” frameborder=“no” src="<%= @journey_poi.sound %>" ></iframe></div>
            <% end %>
            </div>
          </div>
         </div>
      </div>
    </div>
  </div>

</div>

<script type="text/javascript">


var styleOut =
[  {
    "elementType": "labels",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "administrative",
    "elementType": "labels",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "administrative",
    "elementType": "labels.text",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "landscape",
    "elementType": "labels",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "landscape.man_made",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "landscape.natural",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "labels",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "labels.text",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "poi.medical",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "poi.place_of_worship",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "poi.school",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "poi.sports_complex",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "labels",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "labels.text",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "road.local",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#2b383e"
      },
      {
        "weight": 0.5
      }
    ]
  },
  {
    "featureType": "transit",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#0f1416"
      }
    ]
  },
  {
    "featureType": "transit",
    "elementType": "labels",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "transit",
    "elementType": "labels.text",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#00a5b7"
      },
      {
        "weight": 2
      }
    ]
  }
];

<% color_array = []%>
// La Cordee Nantes Lat Lng
var centerMap = new google.maps.LatLng(<%= @poi.latitude %>, <%= @poi.longitude %>);
var myOptions = {
  zoom: 14,
  center: centerMap,
  scrollwheel: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP,
  styles: styleOut,
  mapTypeControl: false,
  streetViewControl: false,
  zoomControl: false
};
var map = new google.maps.Map(document.getElementById('map'), myOptions);


// http://freeiconbox.com/icon/256/34338.png
// http://maps.google.com/mapfiles/kml/shapes/flag.png
// http://maps.google.com/mapfiles/kml/shapes/arrow.png
// http://www.freeiconspng.com/uploads/illuminati-icon-png-29.png
// mapx50.png
// -----------------------------------------------------------
var titre = "La Cordee";
var blue = '#0000FF';
var green = '#00FF00';
var red = '#FF0000';
var yellow = '#F0F000';
var purple = '#FF1AFF';
var orange = '#ff6600';
var all_markers = {};
var counter = 0;
 <% color = ['#ff8b00', '#CD3131', '#d59bf6', '#ffe98a'] %>
<%
  if @journey.id == 1
    actual_color = '#ff8b00'
  elsif @journey.id == 2
    actual_color = '#CD3131'
  elsif @journey.id == 3
    actual_color = '#D59bf6'
  elsif @journey.id == 4
    actual_color = '#ffe98a'
  end
  %>
  var ico = pinSymbol('<%= actual_color %>');

function pinSymbol(color) {
  return {
        path: 'M 9.732 -0.001 c -5.375 0 -9.729 4.356 -9.732 9.73 h 0.004 c 0.025 2.399 1.686 6.169 3.576 9.84 l 4.166 7.42 c 0.852 1.41 1.418 2.301 1.42 2.305 l 0.564 0.885 l 0.564 -0.885 c 0.002 -0.004 0.57 -0.895 1.424 -2.305 l 4.164 -7.418 c 1.889 -3.67 3.547 -7.44 3.578 -9.842 c 0 -5.374 -4.353 -9.73 -9.728 -9.73 z M 9.73 14.037 c -2.596 0 -4.697 -2.104 -4.697 -4.697 s 2.101 -4.697 4.697 -4.697 c 2.594 0 4.697 2.104 4.697 4.697 s -2.103 4.697 -4.697 4.697 z',

        fillColor: color,
        fillOpacity: 1,
        scaledSize: new google.maps.Size(25, 25),
        anchor: new google.maps.Point(9, 30),
        strokeWeight: 0,
        scale: 1,

  }
};


// -----------------------------------------------------------
function marquePoi(lat,lng,ico,titre, visibility) {
  var maLatLng = new google.maps.LatLng(lat, lng);
  if (lat == <%= @poi.latitude %>) {
    ico = pinSymbol('#e6e7e8');
  };
  var marqueur = new google.maps.Marker({
  position: maLatLng,
  map: map,
  title: titre,
  icon: ico,
  visible: visibility
  });
  // marker.addListener('click', function() {
  //         console.log("hi")
  // });
  all_markers[counter] = marqueur
  counter++
  return marqueur;
};

function addToCoordinatesObjectArray(coordinatesArray, lat, lng){
  var newLatLng = new google.maps.LatLng(lat, lng)
  coordinatesArray.push(newLatLng);
};

function createParcours(hashDanslArray, color) {
  var coordinatesArray = []
    for(var i = 0; i < hashDanslArray.length; i++) {
      var lat = hashDanslArray[i][0];
      var lng = hashDanslArray[i][1];
      var total = lat+" "+lng
      addToCoordinatesObjectArray(coordinatesArray, lat, lng);
      marquePoi(lat,lng, ico, total, true)
    }
  var parcoursPath = new google.maps.Polyline({
    path: coordinatesArray,
    geodesic: true,
    strokeColor: color,
    strokeOpacity: 1,
    strokeWeight: 6,
  });
  parcoursPath.setMap(map);
};

function getCoordinatesonClick() {
  var infowindow = null;
  var marqueur = null;
  map.addListener("click", function (event) {
    if (infowindow) {
      infowindow.close();
    }
    var lat = event.latLng.lat();
    var lng = event.latLng.lng();
    infowindow = new google.maps.InfoWindow({
      content: lat + ', ' + lng
    });
    marqueur = marquePoi(lat, lng, ico, "", false)
    infowindow.open(map, marqueur);
  });
};

// -----------------------------------------------------------

// < color = ['#E59500', '#F44336', '#E5DADA', '#52DEE5'] %>
// < @coordinates_hash.each_with_index do |coordinate,i| %>
// createParcours(<= coordinate %>, '<= color[i] %>');
// < end %>



  createParcours(<%= @coordinates_hash[0] %>, '<%= actual_color %>');
  // marquePoi(<%= @poi.latitude %>, <%= @poi.longitude %>, 'http://maps.google.com/mapfiles/ms/icons/red-dot.png' ,'current marker', true);

</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>